---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: document
  path: Pricing.md
  label: Pricing
  match: "**/*"
- type: document
  path: Home.md
  label: Home
  read_only: true
- type: jekyll-posts
  label: About
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
